/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        // ── Spatia Design System ──────────────────────────────
        'sp-green':       '#1E686E',
        'sp-green-light': '#E3EFEF',
        'sp-green-accent':'#1E686E',
        'sp-heading':     '#111827',
        'sp-body':        '#4B5563',
        'sp-border':      '#E8ECEB',

        // ── Legacy tokens (keep for tech page) ───────────────
        'outline-variant':            '#c6c6cb',
        'surface-bright':             '#fcf8f8',
        'on-primary-fixed-variant':   '#44474d',
        'tertiary':                   '#000000',
        'surface-container-high':     '#ebe7e7',
        'secondary-fixed-dim':        '#8fd2d8',
        'on-surface':                 '#1c1b1c',
        'on-primary-container':       '#81848a',
        'on-secondary-fixed-variant': '#004f54',
        'primary-fixed':              '#e1e2e9',
        'inverse-primary':            '#c4c6cd',
        'on-tertiary':                '#ffffff',
        'surface-tint':               '#5c5e65',
        'primary-container':          '#191c21',
        'inverse-on-surface':         '#f3f0f0',
        'on-error':                   '#ffffff',
        'surface':                    '#fcf8f8',
        'secondary-fixed':            '#aaeef5',
        'error-container':            '#ffdad6',
        'outline':                    '#76777b',
        'on-tertiary-fixed-variant':  '#38485d',
        'surface-dim':                '#dcd9d9',
        'on-primary-fixed':           '#191c21',
        'surface-variant':            '#e5e2e2',
        'primary':                    '#000000',
        'on-error-container':         '#93000a',
        'on-surface-variant':         '#45474b',
        'inverse-surface':            '#313031',
        'tertiary-container':         '#0b1c30',
        'on-tertiary-container':      '#75859d',
        'surface-container':          '#f1eded',
        'secondary':                  '#01ac95',
        'on-background':              '#1c1b1c',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f6f3f3',
        'on-tertiary-fixed':          '#0b1c30',
        'secondary-container':        '#aaeef5',
        'on-secondary-fixed':         '#002022',
        'tertiary-fixed':             '#d3e4fe',
        'primary-fixed-dim':          '#c4c6cd',
        'on-secondary-container':     '#266e74',
        'background':                 '#fcf8f8',
        'on-primary':                 '#ffffff',
        'error':                      '#ba1a1a',
        'surface-container-highest':  '#e5e2e2',
        'on-secondary':               '#ffffff',
        'tertiary-fixed-dim':         '#b7c8e1',
      },
      fontFamily: {
        inter:              ['Inter', 'sans-serif'],
        // legacy
        'mono-technical':   ['Geist', 'monospace'],
        'label-sm':         ['Geist', 'sans-serif'],
        'headline-md':      ['Inter', 'sans-serif'],
        'body-lg':          ['Inter', 'sans-serif'],
        'body-md':          ['Inter', 'sans-serif'],
        'headline-lg':      ['Inter', 'sans-serif'],
        'display-xl':       ['Inter', 'sans-serif'],
      },
      fontSize: {
        // legacy
        'mono-technical': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-sm':       ['13px', { lineHeight: '1',   letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md':    ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg':        ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md':        ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg':    ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-xl':     ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg:   '2rem',
        xl:   '3rem',
        full: '9999px',
      },
      spacing: {
        unit:            '8px',
        gutter:          '24px',
        'container-max': '1440px',
        'margin-mobile': '20px',
        'margin-desktop':'64px',
      },
      maxWidth: {
        'container':     '1280px',
        'container-max': '1440px',
      },
      animation: {
        'float':      'float 4s ease-in-out infinite',
        'ping-slow':  'ping 2.5s cubic-bezier(0,0,0.2,1) infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-8px)' },
        },
      },
    },
  },
  plugins: [],
};
